[dev]
  framework = "gatsby"
  command = "yarn start" # Command to start your dev server
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
[build]
  memory = 6000
  publish = "public"
  command = "yarn build:prod"
  framework = "gatsby"
[build.environment]
  NODE_VERSION = "22.1.0"
  YARN_VERSION = "4.1.0"
[[plugins]]
  package = "@netlify/plugin-gatsby"
