[build] # Make sure you don't have a duplicate [build] context!
  functions = "packages/netlify-functions/"

[dev]
  framework = "gatsby"
  command = "yarn start" # Command to start your dev server
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
