[dev]
  framework = "gatsby"
  command = "yarn start" # Command to start your dev server
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
[build]
  memory = 7000
  publish = "public"
  command = "yarn build"
[build.environment]
  NODE_VERSION = "22.1.0"
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "4.1.0" #or other version
[build.processing]
  skip_processing = true
[[plugins]]
  package = "@netlify/plugin-gatsby"
