module.exports = {
    nodeTypes: {
        teams: 'teams',
        leagueTable: 'leagueTable',
        draft: 'draft',
        managers: 'managers',
        divisions: 'divisions',
        players: 'players',
        gameWeeks: 'gameWeeks',
        cup: 'cup',
        transfers: 'transfers',
        positionCategories: 'positionCategories',
        positions: 'positions',
        skySportsFixtures: 'skySportsFixtures',
        skySportsScores: 'skySportsScores',
        skySportsPlayers: 'skySportsPlayers',
        skySportsPlayerStats: 'skySportsPlayerStats',
        adminPlayersList: 'adminPlayersList',
        fplPositions: 'fplPositions',
        fplEvents: 'fplEvents',
        fplTeams: 'fplTeams',
        fplFixtures: 'fplFixtures',
        fplScores: 'fplScores',
        fplPlayers: 'fplPlayers',
        fplPlayerStats: 'fplPlayerStats',
    },
    mediaTypes: {
        IMG: (type) => `image/${type}`,
        JSON: 'application/json',
        MDX: 'text/markdown',
    },
};
