export default {
    '©': 'copy',
    œ: 'oe',
    Œ: 'OE',
    '∑': 'sum',
    '®': 'r',
    '†': '-',
    '∂': 'd',
    ƒ: 'f',
    '™': 'tm',
    '℠': 'sm',
    '…': '-',
    '˚': 'o',
    º: 'o',
    ª: 'a',
    '•': '-',
    '∆': 'delta',
    '∞': 'infinity',
    '♥': 'love',
    '&': 'and',
    '|': 'or',
    '<': 'less',
    '>': 'greater',
};
